GearAdd = (vehicle player);
GearAdd addWeapon 'arifle_MX_GL_F';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemRadio';
GearAdd addBackpack 'B_Carryall_Base';
GearAdd addPrimaryWeaponItem 'muzzle_snds_H';
GearAdd addPrimaryWeaponItem 'optic_Aco';
GearAdd addPrimaryWeaponItem 'acc_flashlight';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartFueltank', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGeneric', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['TrapBear', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGlass', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartEngine', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemJerrycan', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['Itemtoolbox', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['30Rnd_65x39_caseless_mag_Tracer', 8];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['UGL_FlareWhite_F', 15];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBandage', 3];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemPainkiller', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['Itemmatchbox', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemKnife', 1];
(Unitbackpack GearAdd) addWeaponCargoGlobal ['MeleeHatchet', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemEtool', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartVRotor', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemTankTrap', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemWire', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemSandbag', 4];
(Unitbackpack GearAdd) addItemCargoGlobal ['U_B_Wetsuit', 1];