GearAdd = (vehicle player);
GearAdd addWeapon 'arifle_MX_GL_F';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemGPS';
GearAdd addBackpack 'B_Carryall_Base';
GearAdd addPrimaryWeaponItem 'muzzle_snds_H';
GearAdd addPrimaryWeaponItem 'optic_Aco';
GearAdd addPrimaryWeaponItem 'acc_flashlight';
GearAdd addWeapon 'Binocular';
GearAdd addItem 'NVGoggles';
GearAdd addWeapon 'B_P_Beret';
GearAdd addWeapon 'G_Diving';
(Unitbackpack GearAdd) addItemCargoGlobal ['CombatUniform_cia', 1];
(Unitbackpack GearAdd) addItemCargoGlobal ['U_B_Wetsuit', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 1];
(Unitbackpack GearAdd) addItemCargoGlobal ['ItemHatchet', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemKnife', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartVRotor', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartWoodPile', 1];