GearAdd = (vehicle player);
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'Binocular';
GearAdd addBackpack 'B_Carryall_Base';
(Unitbackpack GearAdd) addItemCargoGlobal ['B_P_Beret', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGeneric', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartWheel', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartGlass', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartEngine', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemJerrycan', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['Itemtoolbox', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['30Rnd_556x45_Stanag', 8];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FlareWhite_M203', 6];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBandage', 3];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemPainkiller', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemHatchet', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemKnife', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartVRotor', 1];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['PartWoodPile', 4];
(Unitbackpack GearAdd) addItemCargoGlobal ['CombatUniform_cia', 1];
(Unitbackpack GearAdd) addItemCargoGlobal ['GhillieSuit', 1];
(Unitbackpack GearAdd) addItemCargoGlobal ['U_B_Wetsuit', 1];
