// config.bin - 01:33:53 05/17/13, generated in 0.13 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

#define true	1
#define false	0

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class CharExtras {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
		version = 0.1;
	};
};
class CfgVehicleClasses
{
	class mbg_usArmy_BDU
	{
		displayName = "MALAK ZOMBIES";
	};
};
class UniformSlotInfo {
	slotType = 0;
	linkProxy = "-";
};
class CfgFaces {
	class Default {
		class Custom;	// External class reference
	};
	
	class Man_A3 : Default {
		class Default {
			displayname = "$STR_CFG_FACES_Default";
			texture = "\A3\Characters_F\Heads\Data\m_White_01_co.paa";
			head = "DefaultHead_A3";
			identityTypes[] = {};
			material = "A3\Characters_F\Heads\Data\m_White_01.rvmat";
			textureHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
			textureHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_1_co.paa";
			materialHL2 = "\A3\Characters_F\Heads\Data\hl_White_hairy_muscular.rvmat";
		};
		
		class Custom : Custom {
			displayname = $STR_CFG_FACES_CUSTOM;
			texture = "#(argb,8,8,3)color(0.596,0.412,0.365,1)";
			head = "DefaultHead_A3";
			identityTypes[] = {};
			material = "A3\Characters_F\Heads\Data\m_White_01.rvmat";
		};
		
		class zedface : Default {
			displayname = "$STR_A3_CfgFaces_Man_A3_PersianHead_A3_010";
			texture = "\CharExtras\textures\m_persian_01_co.paa";
			head = "PersianHead_A3";
			identityTypes[] = {"Head_OO"};
			material = "\CharExtras\textures\m_persian_01_co.paa";
			disabled = 0;
		};
		
		class zedface1 : Default {
			displayname = "$STR_A3_CfgFaces_Man_A3_PersianHead_A3_010";
			texture = "\CharExtras\textures\test_prototypehead_co.paa";
			head = "PersianHead_A3";
			identityTypes[] = {"Head_O1"};
			material = "\CharExtras\textures\test_prototypehead_co.paa";
			disabled = 0;
		};
		
		class zedface2 : Default {
			displayname = "$STR_A3_CfgFaces_Man_A3_PersianHead_A3_010";
			texture = "\CharExtras\textures\m_white_02_co.paa";
			head = "PersianHead_A3";
			identityTypes[] = {"Head_O2"};
			material = "\CharExtras\textures\m_white_02_co.paa";
			disabled = 0;
		};
	};
};
class cfgWeapons {
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class U_B_HeliPilotCoveralls;	// External class reference
	class HeadgearItem;	// External class reference
	class Uniform_Base;	// External class reference
	class UniformItem;	// External class reference
	class ItemInfo;	// External class reference
	class U_BasicBody;	// External class reference
	class O_Soldier_base_F;	// External class reference
	class U_O_CombatUniform_ocamo;	// External class reference
	class U_B_CombatUniform_mcam_vest;	// External class reference
	class Vest_Base;	// External class reference
	class VestItem;	// External class reference
	class V_Rangemaster_belt;	// External class reference
	class H_Cap_red;	// External class reference
	class H_MilCap_ocamo;	// External class reference
	class H_HelmetB;	// External class reference
	class H_HelmetO_ocamo;	// External class reference
	class H_Booniehat_khk;	// External class reference
	class V_TacVest_khk;	// External class reference
	class V_HarnessO_brn;	// External class reference
	class V_RebreatherB;	// External class reference
	class U_O_PilotCoveralls;	// External class reference
	
	class U_B_BasicBody : Uniform_Base {
		scope = public;
		displayName = "U_B_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_B";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	class CombatUniform_cia : Uniform_Base {
		scope = 2;
		displayName = "Bandit Uniform";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "malakbandit";
			containerClass = "Supply20";
			mass = 50;
		};
	};
	class U_O_BasicBody : Uniform_Base {
		scope = public;
		displayName = "U_O_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_O";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_Retro_BasicBody : Uniform_Base {
		scope = public;
		displayName = "U_Retro_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_Retro";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_Brown_BasicBody : Uniform_Base {
		scope = public;
		displayName = "U_Brown_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_Brown";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_Blue_BasicBody : Uniform_Base {
		scope = public;
		displayName = "U_Blue_BasicBody";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Underwear_Blue";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	
	class U_O_CombatUniform_oucamo : U_O_CombatUniform_ocamo {
		scope = public;
		displayName = "U_O_CombatUniform_oucamo";
		picture = "\A3\characters_f\data\ui\icon_u_oi_combatuniform_oucamo_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver.p3d";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "O_USoldier_F";
			containerClass = "Supply20";
			mass = 80;
		};
	};
	
	class U_O_Officer_uniform : U_O_CombatUniform_ocamo {
		scope = public;
		displayName = "U_O_Officer_uniform";
		picture = "\A3\characters_f\data\ui\icon_U_B_CombatUniform_mcam_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver.p3d";
		moves = "CfgMovesZombie"; 
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "Officer_soldier";
			containerClass = "Supply20";
			mass = 80;
		};
	};
	
	class U_C_Poloshirt_Pants : Uniform_Base {
		scope = public;
		displayName = "U_C_Poloshirt_Pants";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_RangeMaster";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	class U_C_Polo : Uniform_Base {
		scope = public;
		displayName = "survivor Uniform";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Range";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	class U_C_Citizen_clothes1 : Uniform_Base {
		scope = public;
		displayName = "U_C_Citizen_clothes1";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_ManJeans1";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Citizen_clothes2 : Uniform_Base {
		scope = public;
		displayName = "U_C_Citizen_clothes2";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_ManJeans2";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Citizen_clothes3 : Uniform_Base {
		scope = public;
		displayName = "U_C_Citizen_clothes2";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_ManJeans3";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Citizen_clothes4 : Uniform_Base {
		scope = public;
		displayName = "U_C_Citizen_clothes2";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_ManJeans4";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_RU_Wetsuit : Uniform_Base {
		scope = public;
		displayName = "$U_RU_Wetsuit";
		picture = "\A3\characters_f\data\ui\icon_u_oi_wetsuit_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "RU_diver_F";
			containerClass = "Supply90";
			uniformType = "Neopren";
			mass = 90;
		};
	};
	
	class U_G_Coveralls_Urban_Camo : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_G_Coveralls_Urban_Camo";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "G_Helipilot_Urban";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Coverall_bandit : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_C_Coverall_bandit";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Bandit";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Coverall_black : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_C_Coverall_black";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Coverall_black";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Coverall_dirty : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_C_Coverall_dirty";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Coverall_dirty";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_C_Coverall_grey : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_C_Coverall_grey";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Coverall_grey";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	class U_C_Hunter : U_C_Coverall_grey {
		scope = public;
		displayName = "U_C_Hunter";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_man_hunt";
			containerClass = "Supply30";
			mass = 30;
		};
	};
	class U_OrestesDN : Uniform_Base {
		scope = 2;
		displayName = "$STR_A3_jacket_shorts";
		picture = "\A3\characters_f\data\ui\icon_U_BasicBody_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_Ores";
			containerClass = "Supply0";
			mass = 1;
		};
	};
	class U_C_Po2 : Uniform_Base {
		scope = 2;
		displayName = "$STR_A3_worn_clothes1";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_man_p_beg";
			containerClass = "Supply30";
			mass = 30;
		};
	};
	class U_C_Worke : Uniform_Base {
		scope = 2;
		displayName = "$STR_A3_worker_overalls";
		picture = "\A3\characters_f\data\ui\icon_U_Citizen_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "C_man_w_worke";
			containerClass = "Supply30";
			mass = 30;
		};
	};
	class U_O_Coveralls_Scientist : U_B_HeliPilotCoveralls {
		scope = public;
		displayName = "U_O_Coveralls_Scientist";
		picture = "\A3\characters_f\data\ui\U_B_HeliPilotCoveralls.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "O_Coverall_scientist";
			containerClass = "Supply10";
			mass = 60;
		};
	};
	
	class U_B_PilotCoveralls : U_O_PilotCoveralls {
		scope = public;
		displayName = "U_B_PilotCoveralls";
		picture = "\A3\characters_f\data\ui\icon_u_b_pilotcoveralls_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "B_Pilot_F";
			containerClass = "Supply50";
			mass = 90;
		};
	};
	
	class U_R_PilotCoveralls : U_O_PilotCoveralls {
		scope = public;
		displayName = "U_R_PilotCoveralls";
		picture = "\A3\characters_f\data\ui\icon_U_OI_PilotCoveralls_ca.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_blufor_diver";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "R_Pilot_F";
			containerClass = "Supply50";
			mass = 90;
		};
	};
	
	class V_RebreatherIR : V_RebreatherB {
		picture = "\A3\characters_f\Data\UI\icon_V_RebreatherIR_CA.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_iran_co.paa"};
		hiddenUnderwaterSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_iran_co.paa", "\A3\characters_f\common\data\diver_equip_iran_co.paa", "\A3\characters_f\data\visors_ca.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\Common\equip_rebreather";
			containerClass = "Supply0";
			mass = 130;
			hiddenSelections[] = {"camo"};
			vestType = "Rebreather";
			hiddenUnderwaterSelections[] = {"hide"};
			shownUnderwaterSelections[] = {"unhide", "unhide2"};
			hiddenUnderwaterSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_iran_co.paa", "\A3\characters_f\common\data\diver_equip_iran_co.paa", "\A3\characters_f\data\visors_ca.paa"};
			armor = 5*0.2;
			passThrough = 0.8;
		};
	};
	
	class V_RebreatherRU : V_RebreatherB {
		picture = "\A3\characters_f\Data\UI\icon_v_rebreatherru_ca.paa";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_rus_co.paa"};
		hiddenUnderwaterSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_rus_co.paa", "\A3\characters_f\common\data\diver_equip_rus_co.paa", "\A3\characters_f\data\visors_ca.paa"};
		
		class ItemInfo : VestItem {
			uniformModel = "\A3\Characters_F\Common\equip_rebreather";
			containerClass = "Supply0";
			mass = 130;
			hiddenSelections[] = {"camo"};
			vestType = "Rebreather";
			hiddenUnderwaterSelections[] = {"hide"};
			shownUnderwaterSelections[] = {"unhide", "unhide2"};
			hiddenUnderwaterSelectionsTextures[] = {"\A3\characters_f\common\data\diver_equip_rus_co.paa", "\A3\characters_f\common\data\diver_equip_rus_co.paa", "\A3\characters_f\data\visors_ca.paa"};
			armor = 5*0.2;
			passThrough = 0.8;
		};
	};
	
	class V_TacVest_blck : V_TacVest_khk {
		displayName = "V_TacVest_blck";
		picture = "\A3\characters_f\Data\UI\icon_v_tacvest_blk_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\tacticalvest_black_co.paa"};
	};
	
	class V_TacVest_blckPol : V_TacVest_khk {
		displayName = "V_TacVest_BlckPol";
		picture = "\A3\characters_f\Data\UI\icon_v_tacvest_blk_police_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\tacticalvest_police_co.paa"};
	};
	
	class V_TacVest_woodcam : V_TacVest_khk {
		displayName = "V_TacVest_woodcam";
		picture = "\A3\characters_f\Data\UI\icon_v_tacvest_camo_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\tacticalvest_camo_co.paa"};
	};
	
	class H_HelmetO_ou_camo : H_HelmetO_ocamo {
		displayName = "H_HelmetO_ou_camo";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetO_ocamo_CA.paa";
		hiddenSelectionsTextures[] = {"\A3\characters_f\OPFOR\data\tech_oucamo_co.paa"};
	};
	
	class H_Helmet_O_Spec : H_HelmetO_ocamo {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "H_Helmet_O_Spec";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetO_ocamo_CA.paa";
		model = "\A3\Characters_F\OPFOR\headgear_o_helmet_ballistic_spec";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\tech_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 130;
			uniformModel = "\A3\Characters_F\OPFOR\headgear_o_helmet_ballistic_spec";
			modelSides[] = {0, 3};
			armor = 3*0.6;
			passThrough = 0.75;
			hiddenSelections[] = {"camo"};
		};
	};
	class H_Kufiya_cbr: H_Booniehat_khk {
	    scope = public;
		weaponPoolAvailable = 1;
        displayName = "Kufiya (Bandit)";
        picture = "\A3\characters_f\Data\UI\icon_H_Booniehat_CA.paa";
        model = "CharExtras\headgear_b_kufiya";
        hiddenSelections[] = {"camo"};
        hiddenSelectionsTextures[] = {"CharExtras\textures\kufiya_co.paa"};
		
        class ItemInfo: HeadgearItem {
            mass = 5;
            uniformModel = "CharExtras\headgear_b_kufiya";
            modelSides[] = {0, 3};
			armor = 3*0.6;
            passThrough = 0.95;
			hiddenSelections[] = {"camo"};
        };
    };
	class H_Helmet_OU_Spec : H_HelmetO_ocamo {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "H_Helmet_OU_Spec";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetO_ocamo_CA.paa";
		model = "\A3\Characters_F\OPFOR\headgear_o_helmet_ballistic_spec";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 130;
			uniformModel = "\A3\Characters_F\OPFOR\headgear_o_helmet_ballistic_spec";
			modelSides[] = {0, 3};
			armor = 3*0.6;
			passThrough = 0.75;
			hiddenSelections[] = {"camo"};
		};
	};
	
	class H_PilotHelmetFighter_O : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "OPFOR Fighter Pilot Helmet";
		picture = "\A3\characters_f\Data\UI\icon_h_pilothelmetfighter_oi_ca.paa";
		Model = "\A3\characters_f\common\headgear_helmet_pilot";
		hiddenSelections[] = {"camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\common\Data\pilot_helmet_iran_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\common\headgear_helmet_pilot";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
			hiddenSelections[] = {"camo2"};
		};
	};
	
	class H_PilotHelmetFighter_B : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "BLUFOR Fighter Pilot Helmet";
		picture = "\A3\characters_f\Data\UI\icon_h_pilothelmetfighter_b_ca.paa";
		Model = "\A3\characters_f\common\headgear_helmet_pilot";
		hiddenSelections[] = {"camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\common\Data\pilot_helmet_nato_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\common\headgear_helmet_pilot";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
			hiddenSelections[] = {"camo2"};
		};
	};
	
	class H_PilotHelmetFighter_R : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "Russian Fighter Pilot Helmet";
		picture = "\A3\characters_f\Data\UI\icon_h_pilothelmetfighter_b_ca.paa";
		Model = "\A3\characters_f\common\headgear_helmet_pilot";
		hiddenSelections[] = {"camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\common\Data\pilot_helmet_rus_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\common\headgear_helmet_pilot";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
			hiddenSelections[] = {"camo2"};
		};
	};
	
	class H_HelmetB_plain : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "Plain Helmet";
		picture = "\A3\characters_f\Data\UI\icon_h_helmetb_ca.paa";
		model = "\A3\characters_f\blufor\headgear_b_helmet_plain";
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\blufor\headgear_b_helmet_plain";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
		};
	};
	
	class H_Cap_bis : H_Cap_red {
		displayName = "H_Cap_bis";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_bis_co.paa"};
	};
	
	class H_Cap_black : H_Cap_red {
		displayName = "H_Cap_black";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_blk_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_black_co.paa"};
	};
	
	class H_Cap_cmmg : H_Cap_red {
		displayName = "H_Cap_cmmg";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_blk_cmmg_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_cmmg_co.paa"};
	};
	
	class H_Cap_green : H_Cap_red {
		displayName = "H_Cap_green";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_green_co.paa"};
	};
	
	class H_Cap_ion : H_Cap_red {
		displayName = "H_Cap_ion";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_blk_ion_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_ion_co.paa"};
	};
	
	class H_Cap_iran : H_Cap_red {
		displayName = "H_Cap_iran";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_tan_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_iran_co.paa"};
	};
	
	class H_Cap_police : H_Cap_red {
		displayName = "H_Cap_police";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_blu_police_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_police_co.paa"};
	};
	
	class H_Cap_raven : H_Cap_red {
		displayName = "H_Cap_raven";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_blk_raven_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_raven_co.paa"};
	};
	
	class H_Cap_surf : H_Cap_red {
		displayName = "H_Cap_surf";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_surfer_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_surf_co.paa"};
	};
	
	class H_Cap_tan : H_Cap_red {
		displayName = "H_Cap_tan";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_tan_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_tan_co.paa"};
	};
	
	class H_Cap_uk : H_Cap_red {
		displayName = "H_Cap_uk";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_khaki_specops_uk_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_uk_co.paa"};
	};
	
	class H_Cap_us : H_Cap_red {
		displayName = "H_Cap_us";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\capb_us_co.paa"};
	};
	
	class H_MilCap_grey : H_MilCap_ocamo {
		displayName = "H_MilCap_grey";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_grey_co.paa"};
		model = "\A3\Characters_F\Common\cappatrol_gry";
	};
	
	class H_MilCap_blu : H_MilCap_ocamo {
		displayName = "H_MilCap_blu";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		model = "\A3\Characters_F\Common\cappatrol_gry";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_blue_co.paa"};
	};
	
	class H_MilCap_check1 : H_MilCap_ocamo {
		displayName = "H_MilCap_check1";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_check1_co.paa"};
		model = "\A3\Characters_F\Common\cappatrol_gry";
	};
	
	class H_MilCap_check2 : H_MilCap_ocamo {
		displayName = "H_MilCap_check2";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		model = "\A3\Characters_F\Common\cappatrol_gry";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_check2_co.paa"};
	};
	
	class H_MilCap_check3 : H_MilCap_ocamo {
		displayName = "H_MilCap_check3";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_check3_co.paa"};
		model = "\A3\Characters_F\Common\cappatrol_gry";
	};
	
	class H_MilCap_tn : H_MilCap_ocamo {
		displayName = "H_MilCap_tn";
		picture = "\A3\characters_f\Data\UI\icon_h_cap_grn_bi_ca.paa";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\cappatrol_tan_co.paa"};
		model = "\A3\Characters_F\Common\cappatrol_gry";
	};
	
	class H_Booniehat_Indp : H_Booniehat_khk {
		displayName = "$H_Booniehat_Indp";
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\booniehat_indp_co.paa"};
	};
	
	class H_Watchcap_blk : ItemCore {
		scope = public;
		weaponPoolAvailable = 1;
		displayName = "Watch Cap - Black";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"a3\characters_f\common\data\woolhat_black_co.paa", "a3\characters_f\common\data\headset_3_co.paa"};
		picture = "\A3\characters_f\Data\UI\icon_h_beret_blk_ca.paa";
		model = "\A3\characters_f\Civil\headgear_beaniehat01";
		
		class ItemInfo : HeadgearItem {
			mass = 100;
			uniformModel = "\A3\characters_f\Civil\headgear_beaniehat01";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.8;
			hiddenSelections[] = {"camo"};
		};
	};
};



class CfgVehicles {
	class B_Bergen_Base;	// External class reference
	class B_Kitbag_Base;	// External class reference
	class B_Carryall_Base;	// External class reference
	class B_FieldPack_ocamo_Medic;	// External class reference
	class B_FieldPack_cbr_Repair;	// External class reference
	class B_FieldPack_cbr_LAT;	// External class reference
	class B_Carryall_ocamo_Exp;	// External class reference
	class man;	// External class reference
	class Civilian_F;	// External class reference
	class O_Soldier_base_F;	// External class reference
	class B_Soldier_diver_base_F;	// External class reference
	class O_Soldier_diver_base_F;	// External class reference
	class B_Soldier_base_F;	// External class reference
	class C_man_1 : Civilian_F {};
	
	class B_Kitbag_digi : B_Kitbag_Base {
		scope = public;
		displayName = "B_Kitbag_digi";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_fast_digi_co.paa"};
	};
	
	class B_Bergen_mcamo : B_Bergen_Base {
		scope = public;
		displayName = "B_Bergen_mcamo";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack1_mcamo_co.paa"};
	};
	
	class B_Bergen_ocamo : B_Bergen_Base {
		scope = public;
		displayName = "B_Bergen_ocamo";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack1_hex_co.paa"};
	};
	
	class B_Bergen_rgr : B_Bergen_Base {
		scope = public;
		displayName = "B_Bergen_rgr";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack1_rgr_co.paa"};
	};
	
	class B_Bergen_blk : B_Bergen_Base {
		scope = public;
		displayName = "B_Bergen_blk";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack1_blk_co.paa"};
	};
	
	class B_Carryall_khk : B_Carryall_Base {
		scope = public;
		displayName = "B_Carryall_khk";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_tortila_khk_co.paa"};
	};
	
	class B_Carryall_cbr : B_Carryall_Base {
		scope = public;
		displayName = "B_Carryall_cbr";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_tortila_cbr_co.paa"};
	};
	
	class B_Carryall_blk : B_Carryall_Base {
		scope = public;
		displayName = "B_Carryall_blk";
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_tortila_blk_co.paa"};
	};
	
	class B_FieldPack_oucamo_Medic : B_FieldPack_ocamo_Medic {
		scope = public;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_gorod_oucamo_co.paa"};
		displayName = "B_FieldPack_oucamo_Medic";
	};
	
	class B_FieldPack_oucamo_Repair : B_FieldPack_cbr_Repair {
		scope = public;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_gorod_oucamo_co.paa"};
		displayName = "B_FieldPack_oucamo_Repair";
	};
	
	class B_FieldPack_oucamo_LAT : B_FieldPack_cbr_LAT {
		scope = public;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_gorod_oucamo_co.paa"};
		displayName = "B_FieldPack_oucamo_LAT";
	};
	
	class B_Carryall_oucamo_Exp : B_Carryall_ocamo_Exp {
		scope = public;
		hiddenSelectionsTextures[] = {"\A3\weapons_f\ammoboxes\bags\data\backpack_tortila_oucamo_co.paa"};
		displayName = "B_Carryall_oucamo_Exp";
	};
	
	class B_Soldier_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_Soldier_lite_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_Soldier_GL_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_soldier_AR_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_Soldier_SL_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_Soldier_TL_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_soldier_M_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_soldier_LAT_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_medic_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_soldier_repair_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_soldier_exp_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_Helipilot_F : B_Soldier_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_diver_F : B_Soldier_diver_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_diver_TL_F : B_Soldier_diver_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class B_diver_exp_F : B_Soldier_diver_base_F {
		nakedUniform = "U_B_BasicBody";
	};
	
	class O_Soldier_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_lite_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_GL_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_AR_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_SL_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_TL_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_soldier_M_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_Soldier_LAT_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_medic_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_soldier_repair_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_soldier_exp_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_helipilot_F : O_Soldier_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_diver_F : O_Soldier_diver_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_diver_TL_F : O_Soldier_diver_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_diver_exp_F : O_Soldier_diver_base_F {
		nakedUniform = "U_O_BasicBody";
	};
	
	class O_USpecOpCQB_F : O_Soldier_F {
		displayName = "Soldier SF - CQB";
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_TacVest_blck", "H_Helmet_OU_Spec", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_TacVest_blck", "H_Helmet_OU_Spec", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		weapons[] = {"arifle_Khaybar_C_ACO_flash_snds_F", "hgun_Rook40_F", "Throw", "Put", "Binocular"};
		respawnWeapons[] = {"arifle_Khaybar_C_ACO_flash_snds_F", "hgun_Rook40_F", "Throw", "Put", "Binocular"};
	};
	
	class O_USoldier_F : O_Soldier_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_lite_F : O_Soldier_lite_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_BandollierB_cbr", "H_MilCap_blu", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_BandollierB_cbr", "H_MilCap_blu", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_GL_F : O_Soldier_GL_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_AR_F : O_Soldier_AR_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_SL_F : O_Soldier_SL_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemGPS", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemGPS", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_TL_F : O_Soldier_TL_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemGPS", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemGPS", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_Usoldier_M_F : O_soldier_M_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class O_USoldier_LAT_F : O_Soldier_LAT_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		backpack = "B_FieldPack_oucamo_LAT";
	};
	
	class O_Umedic_F : O_medic_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		backpack = "B_FieldPack_oucamo_Medic";
	};
	
	class O_Usoldier_repair_F : O_soldier_repair_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		nakedUniform = "U_O_BasicBody";
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		backpack = "B_FieldPack_oucamo_Repair";
	};
	
	class O_Usoldier_exp_F : O_soldier_exp_F {
		vehicleClass = "MenUrban";
		uniformClass = "U_O_CombatUniform_oucamo";
		nakedUniform = "U_O_BasicBody";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\clothing_oucamo_co.paa", "\A3\Characters_F\OPFOR\Data\tech_oucamo_co.paa"};
		linkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_HarnessO_brn", "H_HelmetO_ou_camo", "NVGoggles", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		backpack = "B_Carryall_oucamo_Exp";
	};
	
	class Officer_soldier : O_Soldier_base_F {
		_generalMacro = "O_Soldier_F";
		scope = public;
		vehicleClass = "Men";
		Faction = OPF_F;
		displayName = "Officer";
		model = "\A3\Characters_F\OPFOR\o_officer.p3d";
		modelSides[] = {3, 1};
		uniformAccessories[] = {};
		nakedUniform = "U_O_BasicBody";
		uniformClass = "U_O_Officer_uniform";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\OPFOR\Data\officer_hex_co.paa"};
		weapons[] = {"hgun_Rook40_F", "Throw", "Put", "Binocular"};
		respawnWeapons[] = {"hgun_Rook40_F", "Throw", "Put", "Binocular"};
		magazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "HandGrenade", "SmokeShell"};
		respawnMagazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "HandGrenade", "SmokeShell"};
		items[] = {"FirstAidKit"};
		linkeditems[] = {"H_Cap_iran", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnlinkeditems[] = {"H_Cap_iran", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\OPFOR\Data\officer.rvmat", "A3\Characters_F\OPFOR\Data\officer_injury.rvmat", "A3\Characters_F\OPFOR\Data\officer_injury.rvmat"};
		};
	};
	
	class malaksurvivor : B_Soldier_base_F {
		_generalMacro = "B_Soldier_F";
		scope = public;
		model = "\A3\Characters_F\Civil\c_poloshirtpants.p3d";
		displayName = "Survivor";
		hiddenSelections[] = {"Camo"};
		uniformClass = "U_C_Poloshirt_Pants";
		weapons[] = {"Throw", "Put"};
		respawnWeapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnMagazines[] = {};
		items[] = {};		
		linkeditems[] = {};
		respawnlinkeditems[] = {};
		hiddenSelectionsTextures[] = {"CharExtras\textures\c_poloshirtpants_1_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\Civil\Data\c_poloshirtpants.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat"};
		};
	}; 
	class malakbandit : B_Soldier_base_F {
		scope = public;
		displayName = "Malakbandit";
		nakedUniform = "U_BasicBody";
		uniformClass = "CombatUniform_cia";
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"CharExtras\textures\clothing1_cia_co.paa"};
		weapons[] = {"Throw", "Put"};
		respawnWeapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnMagazines[] = {};
		items[] = {};		
		linkedItems[] = {"V_Rangemaster_belt","H_Kufiya_cbr"};
		respawnLinkedItems[] = {"V_Rangemaster_belt","H_Kufiya_cbr"};
	};
	class malak : B_Soldier_base_F {
		_generalMacro = "B_Soldier_F";
		scope = public;
		model = "\A3\Characters_F\Civil\c_poloshirtpants.p3d";
		displayName = "Malak";
		hiddenSelections[] = {"Camo"};
		uniformClass = "U_C_Poloshirt_Pants";
		weapons[] = {"Throw", "Put"};
		respawnWeapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnMagazines[] = {};
		items[] = {};		
		linkeditems[] = {"V_Rangemaster_belt", "B_P_Beret"};
		respawnlinkeditems[] = {"V_Rangemaster_belt", "B_P_Beret"};
		hiddenSelectionsTextures[] = {"CharExtras\textures\c_poloshirtpants_1_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\Civil\Data\c_poloshirtpants.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat"};
		};
	};
	
	class C_RangeMaster : B_Soldier_base_F {
		_generalMacro = "B_Soldier_F";
		scope = public;
		model = "\A3\Characters_F\Civil\c_poloshirtpants.p3d";
		displayName = "Rangemaster";
		hiddenSelections[] = {"Camo"};
		uniformClass = "U_C_Poloshirt_Pants";
		weapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		respawnWeapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		magazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag"};
		respawnMagazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag"};
		linkeditems[] = {"V_Rangemaster_belt"};
		respawnlinkeditems[] = {"V_Rangemaster_belt"};
		hiddenSelectionsTextures[] = {"CharExtras\textures\c_poloshirtpants_1_co.paa"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\Civil\Data\c_poloshirtpants.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat"};
		};
	};
	class C_Range : B_Soldier_base_F {
		_generalMacro = "B_Soldier_F";
		scope = public;
		model = "\A3\Characters_F\Civil\c_poloshirtpants.p3d";
		displayName = "zombie survivor";
		hiddenSelections[] = {"Camo"};
		uniformClass = "U_C_Poloshirt_Pants";
		weapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		respawnWeapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		magazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag"};
		respawnMagazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "16Rnd_9x21_Mag"};
		linkeditems[] = {"V_Rangemaster_belt"};
		respawnlinkeditems[] = {"V_Rangemaster_belt"};
		hiddenSelectionsTextures[] = {"CharExtras\textures\c_poloshirtpants_1_co.paa"};
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O1"};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\Civil\Data\c_poloshirtpants.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat", "A3\Characters_F\Civil\Data\c_poloshirtpants_injury.rvmat"};
		};
	};
	class zedcombi : Civilian_F {
		scope = protected;
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		_generalMacro = "C_man_1";
		displayName = "zombie 1";
		uniformClass = "U_C_Coverall_grey";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\clothing1_co.paa"};
		cost = 20000;
		camouflage = 2.0;	// how dificult to spot - bigger - better spotable
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O1"};
		linkeditems[] = {"V_Rangemaster_belt", "H_HelmetB_light"};
		respawnlinkeditems[] = {"V_Rangemaster_belt", "H_HelmetB_light"};
		
	};
	
	class zedcombi2 : Civilian_F {
		scope = protected;
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		_generalMacro = "C_man_1";
		displayName = "zombie 2";
		uniformClass = "U_C_Coverall_grey";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\clothing1_co.paa"};
		cost = 20000;
		camouflage = 2.0;	// how dificult to spot - bigger - better spotable
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_OO"};
		linkeditems[] = {"V_Rangemaster_belt"};
		respawnlinkeditems[] = {"V_Rangemaster_belt"};
		
	};
	
	class zedcombi3 : Civilian_F {
		scope = protected;
		model = "\A3\characters_F\BLUFOR\b_soldier_01.p3d";
		_generalMacro = "C_man_1";
		displayName = "zombie 3";
		uniformClass = "U_C_Coverall_grey";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\coveralls_urbancamo_co.paa"};
		cost = 20000;
		camouflage = 2.0;	// how dificult to spot - bigger - better spotable
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O2"};
		linkeditems[] = {"V_Rangemaster_belt"};
		respawnlinkeditems[] = {"V_Rangemaster_belt"};
		
	};
	
	class zedcivil : Civilian_F {
		scope = protected;
		model = "\A3\Characters_F\Civil\c_citizen5.p3d";
		_generalMacro = "C_man_1";
		displayName = "zombie 4";
		uniformClass = "U_C_Coverall_grey";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\c_cloth1_v2_co.paa"};
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O2"};
		
	};
	
	class zedcivil2 : Civilian_F {
		scope = 2;
		model = "\A3\Characters_F\Civil\c_citizen5.p3d";
		_generalMacro = "C_man_1";
		displayName = "zombie 6";
		uniformClass = "U_C_Coverall_grey";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\c_cloth1_black.paa"};
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O2"};
		
	};
	
	class C_man_hunt : C_man_1 {
		scope = 2;
		_generalMacro = "C_man_hunter_1_F";
		model = "\A3\characters_F\civil\c_hunter_f";
		uniformClass = "U_C_Hunter";
		moves = "CfgMovesZombie"; 
		displayName = "hunter";
		linkedItems[] = {"H_Booniehat_grn", "ItemWatch"};
		respawnLinkedItems[] = {"H_Booniehat_grn", "ItemWatch"};
		hiddenSelections[] = {};
	};
	
	class C_ManJeans1 : Civilian_F {
		_generalMacro = "C_man_1";
		scope = protected;
		model = "\A3\Characters_F\Civil\c_citizen5.p3d";
		displayName = "Civilian Jeans 1";
		hiddenSelections[] = {"Camo1"};
		hiddenSelectionsTextures[] = {"\CharExtras\textures\basicbody_black_co.paa", "\CharExtras\textures\c_cloth4_co.paa"};
		uniformClass = "U_C_Coverall_grey";
		moves = "CfgMovesZombie"; 
		head = "MaleAfricanHead_01";
		identityTypes[] = {"Head_O2"};
		linkeditems[] = {};
		respawnlinkeditems[] = {};
	};
	class C_Ores : Civilian_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "C_Orestes";
		model = "\A3\characters_F\civil\c_orestes";
		allowedUniformSides[] = {"U_OrestesBody"};
		displayName = "Orestes";
		vehicleClass = "MenStory";
		nakedUniform = "U_OresDN";
		uniformClass = "";
		moves = "CfgMovesZombie";
		identityTypes[] = {"Head_O2"};
		linkeditems[] = {};
		respawnlinkeditems[] = {};
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\Characters_F\Civil\Data\orestes.rvmat", "A3\Characters_F\Civil\Data\orestes_injury.rvmat", "A3\Characters_F\Civil\Data\orestes_injury.rvmat"};
		};
	};
	class C_man_p_begg : Civilian_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "C_man_p_beggar_F";
		model = "\A3\characters_F\civil\c_poor";
		modelSides[] = {3};
		uniformClass = "U_C_Po2";
		displayName = "$STR_A3_C_man_p_beggar_F0";
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"A3\characters_f\civil\data\c_cloth1_v2_co.paa"};
		moves = "CfgMovesZombie";
		identityTypes[] = {"Head_O2"};
		linkeditems[] = {};
		respawnlinkeditems[] = {};
	};
	class C_man_w_worke : Civilian_F {
		author = "$STR_A3_Bohemia_Interactive";
		_generalMacro = "C_man_w_worker_F";
		model = "\A3\characters_F\common\coveralls";
		modelSides[] = {3};
		uniformClass = "U_C_WorkerCoveralls";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\coveralls_dirty_co.paa"};
		displayName = "$STR_A3_C_man_w_worker_F0";
		moves = "CfgMovesZombie";
		identityTypes[] = {"Head_O2"};
		linkeditems[] = {};
		respawnlinkeditems[] = {};
		
	};
	class O_Pilot_F : O_helipilot_F {
		_generalMacro = "O_helipilot_F";
		scope = public;
		displayName = "Fighter Pilot";
		model = "\A3\characters_F\Common\pilot_f.p3d";
		uniformClass = "U_O_PilotCoveralls";
		linkedItems[] = {"H_PilotHelmetFighter_O", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_PilotHelmetFighter_O", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		weapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		respawnWeapons[] = {"hgun_Rook40_F", "Throw", "Put"};
		magazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "SmokeShell"};
		respawnMagazines[] = {"16Rnd_9x21_Mag", "16Rnd_9x21_Mag", "SmokeShell"};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"\A3\Characters_F\Common\Data\pilot_suit_iran_co.paa", "\A3\Characters_F\Common\Data\pilot_helmet_iran_co.paa"};
		cost = 20000;
		camouflage = 2.0;	// how dificult to spot - bigger - better spotable
		
		class Wounds {
			tex[] = {};
			mat[] = {"A3\characters_f\common\data\pilot_suit.rvmat", "A3\Characters_F\Common\Data\W1_pilot_suit.rvmat", "A3\Characters_F\Common\Data\W1_pilot_suit.rvmat"};
		};
	};
	
};
