// config.bin - 14:36:56 04/28/13, generated in 0.13 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define VSoft		0
#define VArmor		1
#define VAir		2

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

class CfgPatches {
	class dayz_equip {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class CfgVehicleClasses {
	class Survival {
		displayName = "Survival";
	};
};

class RscStandardDisplay {
	access = ReadAndWrite;
	movingEnable = 1;
	enableSimulation = 1;
	enableDisplay = 1;
};

class RscObject {
	access = ReadAndWrite;
	type = 80;
	scale = 1;
	direction[] = {0, 0, 1};
	up[] = {0, 1, 0};
};

class RscPicture {
	access = ReadAndWrite;
	type = VSoft;
	idc = -1;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	style = 0x30 + 0x100;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class RscButton {
	access = ReadAndWrite;
	text = "";
	colorText[] = {0.543, 0.5742, 0.4102, 1};
	colorDisabled[] = {0.4, 0.4, 0.4, 1};
	colorBackground[] = {1, 0.537, 0, 0.5};
	colorBackgroundDisabled[] = {0.95, 0.95, 0.95, 1};
	colorBackgroundActive[] = {1, 0.537, 0, 1};
	colorFocused[] = {1, 0.537, 0, 1};
	colorShadow[] = {0.023529, 0, 0.0313725, 1};
	colorBorder[] = {0.023529, 0, 0.0313725, 1};
	soundEnter[] = {"\ca\ui\data\sound\mouse2", 0.09, 1};
	soundPush[] = {"\ca\ui\data\sound\new1", 0.09, 1};
	soundClick[] = {"\ca\ui\data\sound\mouse3", 0.07, 1};
	soundEscape[] = {"\ca\ui\data\sound\mouse1", 0.09, 1};
	type = VArmor;
	style = 0x02 + 0x100;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	font = "Zeppelin32";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class RscButtonPhone : RscButton {
	colorText[] = {0.543, 0.5742, 0.4102, 0};
	colorDisabled[] = {0.4, 0.4, 0.4, 0};
	colorBackground[] = {1, 0.537, 0, 0};
	colorBackgroundDisabled[] = {0.95, 0.95, 0.95, 0};
	colorBackgroundActive[] = {1, 0.537, 0, 0};
	colorFocused[] = {1, 0.537, 0, 0};
	colorShadow[] = {0.023529, 0, 0.0313725, 0};
	colorBorder[] = {0.023529, 0, 0.0313725, 0};
	soundEnter[] = {"", 0.09, 1};
	soundPush[] = {"", 0.09, 1};
	soundClick[] = {"", 0.07, 1};
	soundEscape[] = {"", 0.09, 1};
};

class RscPhonePicture : RscStandardDisplay {
	class controlsBackground {
		class RscPicture_1200 : RscPicture {
			idc = 1200;
			text = "mphone_CA.paa";
			x = 0.2;
			y = 0.09;
			w = 0.6;
			h = 0.8;
		};
	};
	
	class controls {
		class RscButton_1600 : RscButtonPhone {
			idc = 1600;
			text = "send";
			x = 0.402736;
			y = 0.597677;
			w = 0.0620061;
			h = 0.0620061;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_1.wav", 0.09, 1};
		};
		
		class RscButton_1601 : RscButtonPhone {
			idc = 1601;
			text = "end";
			x = 0.528875;
			y = 0.597677;
			w = 0.0620061;
			h = 0.0620061;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_0.wav", 0.09, 1};
		};
		
		class RscButton_1602 : RscButtonPhone {
			idc = 1602;
			text = "1";
			x = 0.399696;
			y = 0.669873;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_1.wav", 0.09, 1};
		};
		
		class RscButton_1603 : RscButtonPhone {
			idc = 1603;
			text = "2";
			x = 0.472644;
			y = 0.671996;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_2.wav", 0.09, 1};
		};
		
		class RscButton_1604 : RscButtonPhone {
			idc = 1604;
			text = "3";
			x = 0.539514;
			y = 0.671996;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_3.wav", 0.09, 1};
		};
		
		class RscButton_1605 : RscButtonPhone {
			idc = 1605;
			text = "4";
			x = 0.404255;
			y = 0.714465;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_4.wav", 0.09, 1};
		};
		
		class RscButton_1606 : RscButtonPhone {
			idc = 1606;
			text = "5";
			x = 0.472644;
			y = 0.716588;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_5.wav", 0.09, 1};
		};
		
		class RscButton_1607 : RscButtonPhone {
			idc = 1607;
			text = "6";
			x = 0.534954;
			y = 0.716588;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_6.wav", 0.09, 1};
		};
		
		class RscButton_1608 : RscButtonPhone {
			idc = 1608;
			text = "7";
			x = 0.407295;
			y = 0.759056;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_7.wav", 0.09, 1};
		};
		
		class RscButton_1609 : RscButtonPhone {
			idc = 1609;
			text = "8";
			x = 0.472644;
			y = 0.76118;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_8.wav", 0.09, 1};
		};
		
		class RscButton_1610 : RscButtonPhone {
			idc = 1610;
			text = "9";
			x = 0.531915;
			y = 0.76118;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_9.wav", 0.09, 1};
		};
		
		class RscButton_1611 : RscButtonPhone {
			idc = 1611;
			text = "*";
			x = 0.416413;
			y = 0.801525;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_star.wav", 0.09, 1};
		};
		
		class RscButton_1612 : RscButtonPhone {
			idc = 1612;
			text = "0";
			x = 0.471125;
			y = 0.805771;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_0.wav", 0.09, 1};
		};
		
		class RscButton_1613 : RscButtonPhone {
			idc = 1613;
			text = "#";
			x = 0.525836;
			y = 0.803648;
			w = 0.0528875;
			h = 0.0386486;
			soundClick[] = {"\dayz_sfx\action\cell\dtmf_hash.wav", 0.09, 1};
		};
		
		class RscButton_1614 : RscButtonPhone {
			idc = 1614;
			text = "Screen";
			x = 0.416413;
			y = 0.260054;
			w = 0.168389;
			h = 0.299601;
		};
	};
};

class CfgCloudlets {
	class Default;	// External class reference
	
	class BottleGlassShards : Default {
		interval = 0.001;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\GlassShards";
		particleFSNtieth = 1;
		particleFSIndex = 0;
		particleFSFrameCount = 1;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "SpaceObject";
		timerPeriod = 3;
		lifeTime = 2;
		moveVelocity[] = {0, 1, 0};
		rotationVelocity = 2;
		weight = 10;
		volume = 1;
		rubbing = 0;
		size[] = {0.05};
		sizeCoef = 1;
		color[] = {{1, 1, 1, 1}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.5;
		position[] = {0, 0, 0};
		positionVar[] = {0.02, 0.02, 0.02};
		moveVelocityVar[] = {0.2, 1, 0.2};
		rotationVelocityVar = 1;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
	
	class BottleGlassShards2 : Default {
		interval = 0.001;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\GlassShards";
		particleFSNtieth = 1;
		particleFSIndex = 0;
		particleFSFrameCount = 1;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "SpaceObject";
		timerPeriod = 3;
		lifeTime = 2;
		moveVelocity[] = {0, 2, 0};
		rotationVelocity = 2;
		weight = 10;
		volume = 1;
		rubbing = 0;
		size[] = {0.05};
		sizeCoef = 1;
		color[] = {{1, 1, 1, 1}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 1;
		randomDirectionIntensity = 1;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.5;
		position[] = {0, 0.4, 0};
		positionVar[] = {0.04, 0.04, 0.04};
		moveVelocityVar[] = {0.2, 3, 0.2};
		rotationVelocityVar = 0;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 1;
		randomDirectionIntensityVar = 1;
	};
	
	class BottleGlassDust : Default {
		interval = 0.005;
		circleRadius = 0;
		circleVelocity[] = {0, 0, 0};
		particleShape = "\ca\Data\ParticleEffects\Universal\Universal";
		particleFSNtieth = 16;
		particleFSIndex = 12;
		particleFSFrameCount = 8;
		particleFSLoop = 0;
		angleVar = 1;
		animationName = "";
		particleType = "Billboard";
		timerPeriod = 3;
		lifeTime = 0.7;
		moveVelocity[] = {0, 0.7, 0};
		rotationVelocity = 2;
		weight = 1.275;
		volume = 1;
		rubbing = 0;
		size[] = {0.05, 0.15};
		sizeCoef = 1;
		color[] = {{0.5, 0.5, 0.5, 0.1}, {0.5, 0.5, 0.5, 0}};
		colorCoef[] = {1, 1, 1, 1};
		animationSpeed[] = {1000};
		animationSpeedCoef = 1;
		randomDirectionPeriod = 0;
		randomDirectionIntensity = 0;
		onTimerScript = "";
		beforeDestroyScript = "";
		lifeTimeVar = 0.1;
		position[] = {0, 0.4, 0};
		positionVar[] = {0.02, 0.02, 0.02};
		moveVelocityVar[] = {0.2, 0.5, 0.2};
		rotationVelocityVar = 0;
		sizeVar = 0.04;
		colorVar[] = {0.1, 0.1, 0.1, 0};
		randomDirectionPeriodVar = 0;
		randomDirectionIntensityVar = 0;
	};
};

class GlassSmash {
	class BottleGlassShards {
		simulation = "particles";
		type = "BottleGlassShards";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassShards2 {
		simulation = "particles";
		type = "BottleGlassShards2";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassDust {
		simulation = "particles";
		type = "BottleGlassDust";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};

class RscPhoneDisplay {
	access = ReadAndWrite;
	idd = 12;
	enableSimulation = 1;
	enableDisplay = 1;
	movingEnable = 0;
	
	class controlsBackground {};
	
	class controls {
		class RscButton_1600 : RscButton {
			idc = 1600;
			text = "1";
			x = 0.379939;
			y = 0.714465;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1601 : RscButton {
			idc = 1601;
			text = "4";
			x = 0.381459;
			y = 0.771797;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1602 : RscButton {
			idc = 1602;
			text = "7";
			x = 0.387538;
			y = 0.829129;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1603 : RscButton {
			idc = 1603;
			text = "*";
			x = 0.396657;
			y = 0.884338;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1604 : RscButton {
			idc = 1604;
			text = "3";
			x = 0.553192;
			y = 0.718711;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1605 : RscButton {
			idc = 1605;
			text = "6";
			x = 0.551672;
			y = 0.778167;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1606 : RscButton {
			idc = 1606;
			text = "9";
			x = 0.544073;
			y = 0.831252;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1607 : RscButton {
			idc = 1607;
			text = "#";
			x = 0.539514;
			y = 0.884338;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1608 : RscButton {
			idc = 1608;
			text = "0";
			x = 0.468085;
			y = 0.880091;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1609 : RscButton {
			idc = 1609;
			text = "8";
			x = 0.468085;
			y = 0.829129;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1610 : RscButton {
			idc = 1610;
			text = "5";
			x = 0.468085;
			y = 0.778167;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1611 : RscButton {
			idc = 1611;
			text = "2";
			x = 0.468085;
			y = 0.725082;
			w = 0.0635259;
			h = 0.0469146;
		};
		
		class RscButton_1612 : RscButton {
			idc = 1612;
			text = "send";
			x = 0.378419;
			y = 0.631652;
			w = 0.0802433;
			h = 0.0702721;
		};
		
		class RscButton_1613 : RscButton {
			idc = 1613;
			text = "end";
			x = 0.541034;
			y = 0.633775;
			w = 0.0802433;
			h = 0.0702721;
		};
		
		class RscButton_1614 : RscButton {
			idc = 1614;
			text = "Screen";
			x = 0.392097;
			y = 0.206969;
			w = 0.215502;
			h = 0.382414;
		};
	};
	
	class objects {
		class GPS : RscObject {
			idc = 106;
			type = 82;
			inBack = 0;
			enableZoom = 0;
			moving = 0;
			scale = 1.5;
			position[] = {0, 0, 0.25};
			direction[] = {0, 1, 7.2};
			up[] = {0, 0, -1};
			zoomDuration = 1;
			waitForLoad = 0;
			onMouseButtonClick = "_this call usePhone;";
			onObjectMoved = "_this call movePhone;";
			model = "\dayz_equip\models\phone.p3d";
			x = 0.22;
			xBack = 0.72;
			y = 0.925;
			yBack = 0.5;
			z = 0.22;
			zBack = 0.12;
		};
	};
};

class cfgWeapons {
	class Default;	// External class reference
	class ItemCore;	// External class reference
	
	class Loot : Default {
		scope = public;
		value = 0;
		type = VSoft;
		displayName = "Use";
		canDrop = false;
		muzzles[] = {this};
		magazines[] = {"ItemBandage", "ItemHeatPack", "PartWoodPile", "PartFueltank", "PartWheel", "PartGeneric", "PartEngine", "PartVRotor", "PartGlass", "ItemWaterbottle", "ItemWaterbottleUnfilled", "ItemEpinephrine", "ItemMorphine", "ItemBloodbag", "ItemAntibiotic", "ItemPainkiller", "ItemJerrycan", "ItemGenerator", "ItemTent", "ItemSandbag", "ItemTankTrap", "ItemWire", "FoodSteakRaw", "TrashTinCan", "ItemSodaCoke", "ItemSodaPepsi", "ItemSodaMdew", "FoodEdible", "FoodSteakCooked", "FoodCanBakedBeans", "FoodCanSardines", "FoodCanFrankBeans", "FoodCanPasta"};
		modes[] = {this};
		useAction = false;
		useActionTitle = "";
		enableAttack = false;
		showToPlayer = false;
	};
	
	class ItemHatchet : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_41;
		model = "\dayz_equip\models\hatchet.p3d";
		picture = "\dayz_equip\textures\equip_hatchet_CA.paa";
		descriptionShort = $STR_EQUIP_DESC_41;
		
		class ItemActions {
			class Use {
				text = $STR_ACTIONS_CHOPWOOD;
				script = "spawn player_chopWood;";
			};
			
			class Toolbelt {
				text = "Remove from Toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"ItemHatchet"};
				output[] = {"MeleeHatchet"};
			};
		};
	};
	
	class Pistol_Base_F;	// External class reference
	
	class MeleeFlashlight : Pistol_Base_F {
		scope = public;
		canDrop = false;
		model = "\dayz_equip\models\flashlight.p3d";
		modelOptics = "-";
		picture = "\dayz_equip\textures\equip_flashlight_ca.paa";
		magazines[] = {};
		displayName = $STR_EQUIP_NAME_5;
		begin1[] = {};
		begin2[] = {};
		soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		reloadMagazineSound[] = {};
		recoil = "recoil_single_pistol_2outof3";
		recoilProne = "recoil_single_pistol_prone_2outof3";
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		
		class Library {
			libTextDesc = "A flashlight (or torch in British English) is a hand-held portable electric-powered light source. Usually the light source is a small incandescent light bulb or light-emitting diode (LED).";
		};
		descriptionShort = $STR_EQUIP_DESC_5;
		autoFire = false;
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			size = 1;
			innerAngle = 30;
			outerAngle = 80;
			coneFadeCoef = 8;
			intensity = 1500;
			scale[] = {0};
			useFlare = 1;
			dayLight = 0;
			flareSize = 0.75;
				
			class Attenuation {
				start = 1.0;
				constant = 2;
				linear = 0;
				quadratic = 15.0;
				};
			};
	
		
		class ItemActions {
			class Toolbelt {
				text = "Add to toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeFlashlight"};
				output[] = {"ItemFlashlight"};
			};
		};
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.3;
		maxRange = 50;
		maxRangeProbab = 0.04;
	};
	
	class ItemFlashlight : Pistol_Base_F {
		scope = public;
		model = "\dayz_equip\models\flashlight.p3d";
		modelOptics = "-";
		picture = "\dayz_equip\textures\equip_flashlight_ca.paa";
		magazines[] = {};
		displayName = $STR_EQUIP_NAME_5;
		begin1[] = {};
		begin2[] = {};
		soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		reloadMagazineSound[] = {};
		recoil = "recoil_single_pistol_2outof3";
		recoilProne = "recoil_single_pistol_prone_2outof3";
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		
		class Library {
			libTextDesc = "A flashlight (or torch in British English) is a hand-held portable electric-powered light source. Usually the light source is a small incandescent light bulb or light-emitting diode (LED).";
		};
		descriptionShort = $STR_EQUIP_DESC_5;
		autoFire = false;
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			size = 1;
			innerAngle = 30;
			outerAngle = 80;
			coneFadeCoef = 8;
			intensity = 1500;
			scale[] = {0};
			useFlare = 1;
			dayLight = 0;
			flareSize = 0.75;
				
			class Attenuation {
				start = 1.0;
				constant = 2;
				linear = 0;
				quadratic = 15.0;
				};
			};
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.3;
		maxRange = 50;
		maxRangeProbab = 0.04;
	};
	
	
	
	class MeleeFlashlightRed : MeleeFlashlight {
		model = "\dayz_equip\models\flashlight_mil.p3d";
		picture = "\dayz_equip\textures\equip_flashlight_mil_ca.paa";
		displayName = $STR_EQUIP_NAME_6;
		descriptionShort = $STR_EQUIP_DESC_6;
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			size = 1;
			innerAngle = 30;
			outerAngle = 80;
			coneFadeCoef = 8;
			intensity = 1500;
			scale[] = {0};
			useFlare = 1;
			dayLight = 0;
			flareSize = 0.75;
				
			class Attenuation {
				start = 1.0;
				constant = 2;
				linear = 0;
				quadratic = 15.0;
				};
			};
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.3;
		maxRange = 50;
		maxRangeProbab = 0.04;

		
		class ItemActions {
			class Toolbelt {
				text = "Add to toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeFlashlightRed"};
				output[] = {"ItemFlashlightRed"};
			};
		};
	};
	
	class ItemFlashlightRed : ItemFlashlight {
		model = "\dayz_equip\models\flashlight_mil.p3d";
		picture = "\dayz_equip\textures\equip_flashlight_mil_ca.paa";
		displayName = $STR_EQUIP_NAME_6;
		descriptionShort = $STR_EQUIP_DESC_6;
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			size = 1;
			innerAngle = 30;
			outerAngle = 80;
			coneFadeCoef = 8;
			intensity = 1500;
			scale[] = {0};
			useFlare = 1;
			dayLight = 0;
			flareSize = 0.75;
				
			class Attenuation {
				start = 1.0;
				constant = 2;
				linear = 0;
				quadratic = 15.0;
				};
			};
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.3;
		maxRange = 50;
		maxRangeProbab = 0.04;
	
	};
};

class CfgMagazines {
	class CA_Magazine;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class ItemCore;	// External class reference
	
	class UniformItem : InventoryItem_Base_F {
		type = 801;
	};
	
	class Uniform_Base : ItemCore {
		scope = 0;
		allowedSlots[] = {901};
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "B_Soldier_F";
			containerClass = "Supply0";
			mass = 0;
		};
	};
	
	class Utility : CA_Magazine {
		scope = public;         
		count = 1;
		type = 256;
        mass = 1;
		displayName = "";
		model = "";
		picture = "";
		descriptionShort = "";
	};
    
	class ItemKnife : Utility {
		scope = public;              
        mass = 4;
		displayName = $STR_EQUIP_NAME_4;
		model = "\dayz_equip\models\knife_gear.p3d";
		picture = "\dayz_equip\textures\equip_knife_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_4;
	};
	
	class ItemToolbox : Utility {
		scope = public;
        mass = 10;
		displayName = $STR_EQUIP_NAME_2;
		model = "\dayz_equip\models\toolbox.p3d";
		picture = "\dayz_equip\textures\equip_toolbox_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_2;
	};
	
	class ItemEtool : Utility {
		scope = public;
        mass = 10;
		displayName = $STR_EQUIP_NAME_1;
		model = "\dayz_equip\models\etool.p3d";
		picture = "\dayz_equip\textures\equip_etool_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_1;
	};
	
	class ItemMatchbox : Utility {
		scope = public;
        mass = 1;
		displayName = $STR_EQUIP_NAME_3;
		model = "\dayz_equip\models\matchbox_gear.p3d";
		picture = "\dayz_equip\textures\equip_matchbox_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_3;
	};
	
	class ItemBandage : CA_Magazine {
		scope = public;
		count = 1;
		type = 16;
		displayName = $STR_EQUIP_NAME_7;
		model = "\dayz_equip\models\fad.p3d";
		picture = "\dayz_equip\textures\equip_fad_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_7;
		
		class ItemActions {
			class Use {
				text = $STR_BANDAGE_SELF;
				script = "spawn player_useMeds;";
			};
		};
	};
	
	class PartFueltank : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 4);
		displayName = $STR_EQUIP_NAME_8;
		model = "\dayz_equip\models\fueltank.p3d";
		picture = "\dayz_equip\textures\equip_fueltank_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_8;
	};
	
	class PartWheel : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 6);
		displayName = $STR_EQUIP_NAME_9;
		model = "\dayz_equip\models\wheel.p3d";
		picture = "\dayz_equip\textures\equip_wheel_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_9;
	};
	
	class PartGeneric : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 3);
		displayName = $STR_EQUIP_NAME_10;
		model = "\dayz_equip\models\genericparts.p3d";
		picture = "\dayz_equip\textures\equip_genericparts_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_10;
	};
	
	class PartEngine : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 6);
		displayName = $STR_EQUIP_NAME_11;
		model = "\dayz_equip\models\engine.p3d";
		picture = "\dayz_equip\textures\equip_engine_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_11;
	};
	
	class PartWoodPile : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 2);
		displayName = $STR_EQUIP_NAME_40;
		model = "\dayz_equip\models\woodPile.p3d";
		picture = "\dayz_equip\textures\equip_woodPile_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_40;
	};
	
	class PartVRotor : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 6);
		displayName = $STR_EQUIP_NAME_32;
		model = "\dayz_equip\models\vrotor.p3d";
		picture = "\dayz_equip\textures\equip_vrotor_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_32;
	};
	
	class PartGlass : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 2);
		displayName = $STR_EQUIP_NAME_30;
		model = "\dayz_equip\models\carglass.p3d";
		picture = "\dayz_equip\textures\equip_carglass_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_30;
	};
	
	class TrapBear : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = "Bear Trap";
		model = "\dayz_equip\models\bear_trap_gear.p3d";
		picture = "\dayz_equip\textures\equip_bear_trap_ca.paa";
		descriptionShort = "Place to add a bear trap";
		
		class ItemActions {
			class Build {
				text = "Place Trap";
				script = "spawn player_setTrap;";
				create = "BearTrap_DZ";
			};
		};
	};
	
	class FoodDrink : CA_Magazine {
		isWater = 1;
		count = 1;
		type = 256;
		
		class ItemActions {
			class Drink {
				text = $STR_ACTIONS_DRINK;
				script = "spawn player_drink;";
			};
		};
	};
	
	class ItemWaterbottle : FoodDrink {
		scope = public;
		refillable = 1;
		sfx = "drink";
		displayName = $STR_EQUIP_NAME_12;
		model = "\dayz_equip\models\waterbottle_gear.p3d";
		picture = "\dayz_equip\textures\equip_waterbottle_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_12;
	};
	
	class ItemWaterbottleUnfilled : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_13;
		model = "\dayz_equip\models\waterbottle_gear.p3d";
		picture = "\dayz_equip\textures\equip_waterbottle_empty_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_13;
		
		class ItemActions {
			class Fill {
				text = $STR_ACTIONS_FILL_W;
				script = "spawn player_fillWater;";
			};
		};
	};
	
	class ItemSodaCoke : FoodDrink {
		scope = public;
		sfx = "soda";
		displayName = "$STR_EQUIP_NAME_36a";
		model = "\dayz_equip\models\soda_coke.p3d";
		picture = "\dayz_equip\textures\equip_soda_coke_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_36;
	};
	
	class ItemSodaPepsi : ItemSodaCoke {
		displayName = "$STR_EQUIP_NAME_36b";
		model = "\dayz_equip\models\soda_pepsi.p3d";
		picture = "\dayz_equip\textures\equip_soda_pepsi_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_36;
	};
	
	class ItemSodaMdew : ItemSodaCoke {
		displayName = $STR_EQUIP_NAME_37;
		model = "\dayz_equip\models\soda_mdew.p3d";
		picture = "\dayz_equip\textures\equip_soda_mdew_ca.paa";
		descriptionShort = $STR_EQUIP_NAME_37;
	};
	
	class ItemEpinephrine : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_14;
		model = "\dayz_equip\models\epi.p3d";
		picture = "\dayz_equip\textures\equip_epi_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_14;
	};
	
	class ItemMorphine : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_15;
		model = "\dayz_equip\models\morphine.p3d";
		picture = "\dayz_equip\textures\equip_morphine_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_15;
		
		class ItemActions {
			class Use {
				text = $STR_TAKE_MORPHINE;
				script = "spawn player_useMeds;";
			};
		};
	};
	
	class ItemHeatPack : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_42;
		model = "\dayz_equip\models\Heat_pack.p3d";
		picture = "\dayz_equip\textures\equip_heat_pack_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_42;
		
		class ItemActions {
			class Use {
				text = $STR_ACTIONS_HEATPACK;
				script = "spawn player_useMeds;";
			};
		};
	};
	
	class ItemBloodbag : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_16;
		model = "\dayz_equip\models\bloodbag.p3d";
		picture = "\dayz_equip\textures\equip_bloodbag_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_16;
	};
	
	class ItemAntibiotic : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_17;
		model = "\dayz_equip\models\med_antibiotic_gear.p3d";
		picture = "\dayz_equip\textures\equip_antibiotics_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_17;
		
		class ItemActions {
			class Use {
				text = $STR_TAKE_ANTIBIOTIC;
				script = "spawn player_useMeds;";
			};
		};
	};
	
	class ItemPainkiller : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_18;
		model = "\dayz_equip\models\med_painkiller_gear.p3d";
		picture = "\dayz_equip\textures\equip_painkiller_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_18;
		
		class ItemActions {
			class Use {
				text = $STR_TAKE_PAINKILLER;
				script = "spawn player_useMeds;";
			};
		};
	};
	
	class ItemJerrycan : CA_Magazine {
		scope = public;
		count = 1;
		fuelQuantity = 20;
		type = (256 * 3);
		displayName = $STR_EQUIP_NAME_19;
		model = "\dayz_equip\models\jerrycan.p3d";
		picture = "\dayz_equip\textures\equip_jerrycan_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_19;
	};
	
	class ItemJerrycanEmpty : ItemJerrycan {
		fuelQuantity = 0;
		type = (256 * 3);
		displayName = $STR_EQUIP_NAME_39;
		picture = "\dayz_equip\textures\equip_jerrycan_e_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_39;
	};
	
	class ItemGenerator : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 6);
		displayName = $STR_EQUIP_NAME_31;
		model = "\dayz_equip\models\generator_gear.p3d";
		picture = "\dayz_equip\textures\equip_generator_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_31;
	};
	
	class ItemTent : CA_Magazine {
		scope = public;
		count = 1;
		type = (256 * 3);
		displayName = $STR_EQUIP_NAME_20;
		model = "\dayz_equip\models\tentbag_gear.p3d";
		picture = "\dayz_equip\textures\equip_tentbag_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_20;
		
		class ItemActions {
			class Pitch {
				text = $STR_PITCH_TENT;
				script = "spawn player_tentPitch;";
			};
		};
	};
	
	class ItemSandbag : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_21;
		model = "\dayz_equip\models\sandbags.p3d";
		picture = "\dayz_equip\textures\equip_sandbag_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_21;
		
		class ItemActions {
			class Build {
				text = $STR_ACTIONS_BUILD;
				script = "spawn player_build;";
				require[] = {"ItemEtool"};
				create = "Sandbag1_DZ";
			};
		};
	};
	
	class ItemTankTrap : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_22;
		model = "\dayz_equip\models\tank_trap_kit.p3d";
		picture = "\dayz_equip\textures\equip_tanktrap_kit_CA.paa";
		descriptionShort = $STR_EQUIP_DESC_22;
		
		class ItemActions {
			class Build {
				text = $STR_ACTIONS_BUILD;
				script = "spawn player_build;";
				require[] = {"ItemToolbox"};
				create = "Hedgehog_DZ";
			};
		};
	};
	
	class ItemWire : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_23;
		model = "\dayz_equip\models\Fence_wire_kit.p3d";
		picture = "\dayz_equip\textures\equip_fencewire_kit_CA.paa";
		descriptionShort = $STR_EQUIP_DESC_23;
		
		class ItemActions {
			class Build {
				text = $STR_ACTIONS_BUILD;
				script = "spawn player_build;";
				require[] = {"ItemToolbox"};
				create = "Wire_cat1";
			};
		};
	};
	
	class FoodSteakRaw : CA_Magazine {
		scope = public;
		count = 1;
		type = 256;
		displayName = $STR_EQUIP_NAME_24;
		model = "\dayz_equip\models\food_steak_gear.p3d";
		picture = "\dayz_equip\textures\equip_steak_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_24;
	};
	
	class FoodEdible : CA_Magazine {
		isFood = 1;
		count = 1;
		type = 256;
		bloodRegen = 200;
		
		class ItemActions {
			class Eat {
				text = $STR_EAT_FOOD;
				script = "spawn player_eat;";
			};
		};
	};
	
	class FoodSteakCooked : FoodEdible {
		scope = public;
		displayName = $STR_EQUIP_NAME_25;
		model = "\dayz_equip\models\food_steak_cooked_gear.p3d";
		picture = "\dayz_equip\textures\equip_steak_cooked_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_25;
		bloodRegen = 800;
	};
	
	class FoodCanBakedBeans : FoodEdible {
		scope = public;
		displayName = $STR_EQUIP_NAME_26;
		model = "\dayz_equip\models\food_bbtin.p3d";
		picture = "\dayz_equip\textures\equip_bbtin_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_26;
	};
	
	class FoodCanSardines : FoodEdible {
		scope = public;
		displayName = $STR_EQUIP_NAME_27;
		model = "\dayz_equip\models\food_sardinestin.p3d";
		picture = "\dayz_equip\textures\equip_Sardinestin_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_27;
	};
	
	class FoodCanFrankBeans : FoodEdible {
		scope = public;
		displayName = $STR_EQUIP_NAME_28;
		model = "\dayz_equip\models\food_fbtin.p3d";
		picture = "\dayz_equip\textures\equip_fbtin_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_28;
	};
	
	class FoodCanPasta : FoodEdible {
		scope = public;
		displayName = $STR_EQUIP_NAME_29;
		model = "\dayz_equip\models\food_pastatin.p3d";
		picture = "\dayz_equip\textures\equip_pastatin_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_29;
	};
};

class CfgVehicles {
	class NonStrategic;	// External class reference
	
	class BuiltItems : NonStrategic {};
	
	class TrapItems : NonStrategic {};
	
	class Wire_cat1 : BuiltItems {
		scope = public;
		animated = false;
		vehicleClass = "Fortifications";
		icon = "\A3\Structures_F\Walls\Data\UI\map_CncBarrier_F_CA.paa";
		accuracy = 0.3;	// accuracy needed to recognize type of this target
		mapSize = 5.5;
		displayName = "$STR_A3_CfgVehicles_Land_Razorwire_F0";
		model = "\dayz_equip\models\wire_cat1.p3d";
		destrType = "DestructTent";
		armor = 100;
		GhostPreview = "Fort_RazorWirePreview";
	};
	
	class Wire_cat2 : Wire_cat1 {
		displayName = "Wire (CAT2)";
		model = "\dayz_equip\models\wire_cat1.p3d";
	};
	
	class Hedgehog_DZ : BuiltItems {
		scope = public;
		destrType = "DestructNo";
		cost = 100;
		//model = "\ca\misc\jezek_kov";
		icon = "\A3\Structures_F\Walls\Data\UI\map_CncBarrier_F_CA.paa";
		mapSize = 2;
		armor = 400;
		displayName = "Hedgehog (Steel)";
		vehicleClass = "Fortifications";
	};
	
	class Sandbag1_DZ : BuiltItems {
		scope = public;
		destrType = "DestructNo";
		cost = 100;
		displayName = "$STR_A3_CfgVehicles_Land_BagFence_Long_F0";
		model = "A3\Structures_F\Mil\BagFence\BagFence_Long_F.p3d";
		icon = "\A3\Structures_F\Walls\Data\UI\map_CncBarrier_F_CA.paa";
		mapSize = 2;
		armor = 400;
		vehicleClass = "Fortifications";
	};
	
	class Sandbag4_DZ : BuiltItems {
		scope = public;
		destrType = "DestructNo";
		cost = 100;
		displayName = "$STR_A3_CfgVehicles_Land_BagBunker_Small_F0";
		model = "\A3\Structures_F\Mil\BagBunker\BagBunker_Small_F.p3d";
		icon = "\A3\Structures_F\Walls\Data\UI\map_CncBarrier_F_CA.paa";
		mapSize = 2;
		armor = 400;
		vehicleClass = "Fortifications";
	};
	
	class BearTrap_DZ : TrapItems {
		scope = public;
		destrType = "DestructNo";
		displayName = "Bear Trap";
		model = "\dayz_equip\models\bear_trap.p3d";
		
		class Eventhandlers {
			init = "_this execFSM '\z\addons\dayz_code\system\trap_monitor.fsm';";
		};
		
		class AnimationSources {
			class LeftShutter {
				source = "user";
				animPeriod = 0.1;
				initPhase = 1;
			};
			
			class RightShutter {
				source = "user";
				animPeriod = 0.1;
				initPhase = 1;
			};
		};
		
		class UserActions {
			class OpenTrap {
				position = "";
				displayName = "Reset Trap";
				radius = 1.5;
				onlyForPlayer = 0;
				condition = "this animationPhase 'LeftShutter' == 1";
				statement = "this animate ['LeftShutter', 0];this animate ['RightShutter', 0];";
			};
			
			class CloseTrap {
				position = "";
				displayName = "Activate Trap";
				radius = 1.5;
				onlyForPlayer = 0;
				condition = "this animationPhase 'LeftShutter' == 0";
				statement = "this animate ['LeftShutter', 1];this animate ['RightShutter', 1];";
			};
			
			class CollectTrap {
				position = "";
				displayName = "Take Trap";
				radius = 1.5;
				onlyForPlayer = 0;
				condition = "this animationPhase 'LeftShutter' == 1";
				statement = "[0,0,0,['cfgMagazines','TrapBear',this]] call object_pickup;";
			};
		};
	};
	class ReammoBox_F;	// External class reference
	class groundweaponHolder;	// External class reference
	
	class weaponHolder : ReammoBox_F {
		scope = private;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		vehicleClass = "Survival";
		displayName = "Weapon";
		memoryPointSupply = "collect";
		supplyRadius = 3;
		transportMaxWeapons = 0;
		transportMaxMagazines = 0;
		transportMaxBackpacks = 0;
		transportAmmo = 0;
		transportRepair = 0;
		transportFuel = 0;
	};
	
	class groundweaponHolder_Colt1911 : groundweaponHolder {
		scope = public;
		displayName = $STR_WPN_HOLDR_1;
		model = "\dayz_equip\proxy\Colt1911.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','Colt1911'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemHatchet : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_41;
		model = "\dayz_equip\models\hatchet.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','ItemHatchet'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_MeleeCrowbar : groundweaponHolder {
		scope = public;
		displayName = "Crowbar";
		model = "\dayz_equip\models\crowbar.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','MeleeCrowbar'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_huntingrifle : groundweaponHolder {
		scope = public;
		displayName = $STR_WPN_HOLDR_2;
		model = "\dayz_equip\proxy\huntingrifle.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','huntingrifle'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_M4A1 : groundweaponHolder {
		scope = public;
		displayName = $STR_WPN_HOLDR_3;
		model = "\dayz_equip\proxy\M4A1.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','M4A1'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemTent : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_20;
		model = "\dayz_equip\proxy\tentbag.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','ItemTent'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemFlashlight : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_5;
		model = "\dayz_equip\proxy\flashlight.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','ItemFlashlight'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemFlashlightRed : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_6;
		model = "\dayz_equip\proxy\flashlight_mil.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgWeapons','ItemFlashlightRed'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemWaterbottle : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_12;
		model = "\dayz_equip\proxy\waterbottle.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','ItemWaterbottleUnfilled'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemGenerator : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_31;
		model = "\dayz_equip\models\generator.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','ItemGenerator'] execVM '\z\addons\dayz_code\init\object_generator.sqf';";
		};
	};
	
	class groundweaponHolder_ItemToolbox : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_2;
		model = "\dayz_equip\proxy\toolbox.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','ItemToolbox'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartFueltank : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_8;
		model = "\dayz_equip\proxy\fueltank.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartFueltank'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartWheel : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_9;
		model = "\dayz_equip\proxy\wheel.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartWheel'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartGeneric : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_10;
		model = "\dayz_equip\proxy\genericparts.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartGeneric'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartVRotor : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_32;
		model = "\dayz_equip\proxy\vrotor.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartVRotor'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartEngine : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_11;
		model = "\dayz_equip\proxy\engine.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartEngine'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_PartGlass : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_30;
		model = "\dayz_equip\proxy\carglass.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','PartGlass'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemJerrycan : groundweaponHolder {
		scope = public;
		displayName = $STR_EQUIP_NAME_19;
		model = "\dayz_equip\proxy\jerrycan.p3d";
		
		class eventHandlers {
			init = "[(_this select 0),'cfgMagazines','ItemJerrycan'] execVM '\z\addons\dayz_code\init\object_pickupAction.sqf';";
		};
	};
	
	class groundweaponHolder_ItemJerrycanSide : groundweaponHolder_ItemJerrycan {
		model = "\dayz_equip\proxy\jerrycan_side.p3d";
	};
	class Land_TentDome_F;	// External class reference
	
	class TentStorage : Land_TentDome_F {
		vehicleClass = "Survival";
		transportMaxMagazines = 50;
		transportMaxWeapons = 10;
		transportMaxBackpacks = 5;
	};
	
	class CardboardBox : ReammoBox_F {
		accuracy = 1000;	// accuracy needed to recognize type of this target
		vehicleClass = "Survival";
	};
	
	class FoodBox0 : CardboardBox {
		scope = public;
		displayName = $STR_DAYZ_OBJ_1;
		model = "\dayz_equip\models\cardboard_box.p3d";
		
		class TransportWeapons {
			class _xx_ItemMatchbox {
				weapon = "ItemMatchbox";
				count = 3;
			};
			
			class _xx_ItemFlashlight {
				weapon = "ItemFlashlight";
				count = 3;
			};
			
			class _xx_ItemKnife {
				weapon = "ItemKnife";
				count = 3;
			};
		};
		
		class transportmagazines {
			class _xx_FoodCanBakedBeans {
				magazine = "FoodCanBakedBeans";
				count = 6;
			};
			
			class _xx_FoodCanSardines {
				magazine = "FoodCanSardines";
				count = 6;
			};
			
			class _xx_FoodCanFrankBeans {
				magazine = "FoodCanFrankBeans";
				count = 6;
			};
			
			class _xx_FoodCanPasta {
				magazine = "FoodCanPasta";
				count = 6;
			};
		};
	};
	
	class FoodBox1 : FoodBox0 {};
	
	class FoodBox2 : FoodBox0 {};
	
	class MedBox0 : CardboardBox {
		scope = public;
		displayName = $STR_DAYZ_OBJ_2;
		model = "\dayz_equip\models\cardboard_box_med.p3d";
		
		class transportmagazines {
			class _xx_ItemBandage {
				magazine = "ItemBandage";
				count = 10;
			};
			
			class _xx_ItemEpinephrine {
				magazine = "ItemEpinephrine";
				count = 5;
			};
			
			class _xx_ItemMorphine {
				magazine = "ItemMorphine";
				count = 5;
			};
			
			class _xx_ItemBloodbag {
				magazine = "ItemBloodbag";
				count = 5;
			};
			
			class _xx_ItemPainkiller {
				magazine = "ItemPainkiller";
				count = 5;
			};
		};
	};
	
	class Land_Campfire_F;	// External class reference
	
	class Land_Fire_DZ : Land_Campfire_F {
		transportMaxMagazines = 8;
		transportMaxWeapons = 1;
		transportMaxBackpacks = 1;
		
		class TransportMagazines {
			class _xx_PartWoodPile {
				magazine = "PartWoodPile";
				count = "1";
			};
		};
		
		class Eventhandlers {
			init = "_this call eh_localCleanup;";
		};
	};
};

class CfgSounds {
	class trap_bear_0 {
		name = "";
		sound[] = {"\dayz_equip\sound\trap_bear_0", 1, 1, 60};
		titles[] = {};
	};
};
