// config.bin - 18:45:53 09/22/13, generated in 0.00 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

enum {
	 //  = 2,	// Error parsing: Empty enum name
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	STABILIZEDINAXISX = 1,
	STABILIZEDINAXESXYZ = 4,
	STABILIZEDINAXISY = 2,
	STABILIZEDINAXESBOTH = 3,
	DESTRUCTNO = 0,
	STABILIZEDINAXESNONE = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

class CfgPatches {
	class Backwards_hat {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {};
	};
};

class cfgWeapons {
	class ItemCore;	// External class reference
	class InventoryItem_Base_F;	// External class reference
	class HeadgearItem;	// External class reference
	
	class Backwards_hat : ItemCore {
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "TF91 Backwards hat";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		model = "\backwardshat\A3_backwards_hat.p3d";
		
		class ItemInfo : HeadgearItem {
			mass = 2;
			uniformModel = "\backwardshat\A3_backwards_hat.p3d";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.1;
		};
	};
	
	class Tan_Backwards_hat : ItemCore {
		scope = 2;
		weaponPoolAvailable = 1;
		displayName = "Tan Backwards hat";
		picture = "\A3\characters_f\Data\UI\icon_H_HelmetB_CA.paa";
		model = "\backwardshat\A3_backwards_hat.p3d";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\backwardshat\data\capb_tan_co.paa"};
		
		class ItemInfo : HeadgearItem {
			mass = 2;
			uniformModel = "\backwardshat\A3_backwards_hat.p3d";
			modelSides[] = {3, 1};
			armor = 3*0.5;
			passThrough = 0.1;
		};
	};
};
